ALTER TABLE "blog" ADD COLUMN "is_published" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "author" VARCHAR(255), ADD COLUMN "image_alt" VARCHAR(500),
ADD COLUMN "published_at" TIMESTAMP(3), ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "destinations" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
