import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2 } from "@/components/Icon";
import { PageShell } from "@/components/PageShell";
import { site, sourceLinks } from "@/lib/site";

export const metadata: Metadata = { title: "Meet Tevan | Local Founder & Simien Guide", description: "Meet Tesema ‘Tevan’ Mulualem, founder and local guide behind Gondar Simien Tours and the Tevan Local philosophy.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <PageShell>
    <section className="about-hero page-hero"><div className="shell about-hero__grid"><div><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>Our story</span></div><p className="eyebrow eyebrow--copper">Tesema “Tevan” Mulualem</p><h1 className="display">The mountains <em>I call home.</em></h1><p className="lead">“I want people to experience the place I know—not just visit it.”</p></div><div className="about-hero__portrait image-frame"><Image src="/images/tevan-portrait.jpg" alt="Tesema ‘Tevan’ Mulualem standing in the Simien Mountains" fill priority sizes="(max-width: 720px) 100vw, 45vw" /></div></div></section>
    <section className="section"><div className="shell editorial-grid"><div><span className="chapter-index">01</span><h2 className="section-title">Knowing the trail is <em>only the beginning.</em></h2></div><div className="prose prose--large"><p>My name is Tesema, though most travelers know me as Tevan. I am a guide from Gondar, and the Simien Mountains were part of the landscape around home before they became my work.</p><p>Guiding made me notice familiar places differently. A traveler stops for a gelada, asks about terraces, or goes quiet at a viewpoint. I learned that the guide’s role is not just to say “follow me.” It is to help someone understand where they are.</p><p>Gondar Simien Tours grew from that belief: listen first, build the right journey, explain the realities honestly, and leave space for a mountain morning that no schedule can manufacture.</p></div></div></section>
    <section className="section section--dark credentials-section"><div className="shell"><p className="eyebrow eyebrow--copper">Verified local expertise</p><div className="credentials-grid"><div><CheckCircle2 /><span>Founder & lead guide</span><strong>Tesema “Tevan” Mulualem</strong></div><div><CheckCircle2 /><span>Professional qualification</span><strong>Tour Guiding Level IV</strong></div><div><CheckCircle2 /><span>Operating company</span><strong>Simien Ethio Tours</strong></div><div><CheckCircle2 /><span>Based</span><strong>Fasil Castle Street, Gondar</strong></div></div><p className="credential-source">Credentials and licensing are published on the <a href={sourceLinks.operatorAbout} target="_blank" rel="noreferrer">official operating company site ↗</a>.</p></div></section>
    <section className="section tevan-local" id="local"><div className="shell tevan-local__grid"><div><p className="eyebrow eyebrow--copper">Tevan Local</p><h2 className="section-title">Travel local. <em>Leave something behind.</em></h2></div><div><p className="lead">A mountain journey depends on a network: guides, scouts, cooks, drivers, mule handlers, accommodation, food suppliers and community hosts. Tevan Local is a commitment to keep more value close to the people who make the journey possible—and to publish proof as the work grows.</p><div className="local-chain"><span>Traveler</span><i>→</i><span>Local team</span><i>→</i><span>Local business</span><i>→</i><span>Local future</span></div><small>Commitments are not presented as achievements until they are measured and verified.</small></div></div></section>
    <section className="inline-cta"><div className="shell"><p>A note can begin a journey.</p><h2>Tell Tevan what you are curious about.</h2><Link className="button button--copper" href="/plan">Plan with Tevan <ArrowUpRight /></Link><a className="inline-contact" href={`mailto:${site.email}`}>{site.email}</a></div></section>
  </PageShell>;
}
