export type InclusionEntry = {
  id: string;
  title: string;
  tag: string;
  intro?: string;
  href?: string;
  linkLabel?: string;
  included: string[];
  excluded: string[];
  excludedNote?: string;
  note?: string;
};

const dayTripExclusions = [
  "International and domestic flights",
  "Visa / eVisa",
  "Travel insurance",
  "Personal trekking equipment",
  "Personal snacks and drinks",
  "Alcohol",
  "Tips",
  "Personal purchases",
  "Optional activities not listed",
];

const trekExclusions = [
  "International and domestic flights",
  "Visa / eVisa",
  "Travel insurance",
  "Personal sleeping bag unless specifically included",
  "Personal trekking equipment",
  "Alcohol",
  "Personal snacks and extra drinks",
  "Laundry",
  "SIM / mobile data / roaming",
  "Tips",
  "Personal expenses",
  "Medical treatment and emergency evacuation",
  "Optional activities not listed",
];

const cityTourExclusions = [
  "International and domestic flights",
  "Visa / eVisa",
  "Travel insurance",
  "Meals and drinks unless specifically stated",
  "Personal purchases",
  "Tips",
  "Optional attractions not listed",
  "Personal expenses",
];

const comboExclusions = [
  "International flights",
  "Domestic flights unless specifically included",
  "Visa / eVisa",
  "Travel insurance",
  "Personal equipment and expenses",
  "Alcohol",
  "Tips",
  "Laundry",
  "Optional activities not listed",
];

export const inclusionEntries: InclusionEntry[] = [
  {
    id: "simien-day",
    title: "Simien in a Day",
    tag: "1 day · Gondar to Gondar",
    href: "/treks/simien-day-trip",
    linkLabel: "Explore the Simien day trip",
    included: [
      "Private transportation from Gondar to Simien and return",
      "Professional English-speaking local guide",
      "Simien National Park entrance fee",
      "Required park scout / ranger",
      "Fuel and driver",
      "Lunch and drinking water according to the day's arrangement",
      "Short guided walks according to the agreed program",
      "Wildlife and landscape interpretation",
      "Gondar hotel pickup and drop-off",
      "Pre-trip planning and coordination",
    ],
    excluded: dayTripExclusions,
  },
  {
    id: "gelada-country",
    title: "Gelada Country",
    tag: "1 day · Wildlife focus",
    intro: "A day built around the mountains' most distinctive wildlife.",
    included: [
      "Private transportation from and back to Gondar",
      "Professional local wildlife / trekking guide",
      "Simien National Park entrance fee",
      "Required park scout / ranger",
      "Driver and fuel",
      "Lunch and drinking water",
      "Guided wildlife walks and interpretation",
      "Gondar hotel pickup and drop-off",
      "Pre-trip planning and coordination",
    ],
    excluded: dayTripExclusions,
    note: "Wildlife sightings are never guaranteed.",
  },
  {
    id: "imet-gogo-day",
    title: "Imet Gogo & the Great Escarpment",
    tag: "1 day · Big views",
    href: "/simien-mountains#imet-gogo",
    linkLabel: "Read about Imet Gogo",
    included: [
      "Gondar–Simien–Gondar transportation",
      "Professional local trekking guide",
      "Simien National Park entrance fee",
      "Required scout / ranger",
      "Driver and fuel",
      "Lunch / packed lunch and drinking water",
      "Guided hike with wildlife and landscape interpretation",
      "Gondar pickup and drop-off",
      "Pre-trip support",
    ],
    excluded: dayTripExclusions,
  },
  {
    id: "simien-introduction",
    title: "Simien Introduction",
    tag: "2 days · 1 night",
    included: [
      "Private transportation from Gondar to Simien and return",
      "Professional English-speaking trekking guide",
      "Simien National Park entrance fee, trekking / camping permits and scout",
      "Camping accommodation: tents, mattresses, camping and camp-kitchen equipment",
      "Cook / camp support and mule support for agreed group equipment",
      "Breakfast, lunch and dinner",
      "Drinking water, tea and coffee according to the confirmed arrangement",
      "Pre-trip briefing and packing guidance",
      "Gondar pickup / drop-off",
      "Gondar + Simien travel preparation notes after booking",
    ],
    excluded: trekExclusions,
  },
  {
    id: "simien-classic",
    title: "Simien Classic",
    tag: "3 days · 2 nights",
    href: "/treks/3-day-simien-trek",
    linkLabel: "Explore the Simien Classic",
    included: [
      "Private Gondar–Simien–Gondar transportation",
      "Professional English-speaking trekking guide",
      "Simien National Park entrance fee, trekking permits, camping fees and scout",
      "Trekking tents, sleeping mattresses, dining / cooking equipment",
      "Camping crew, cook and mule support for agreed luggage",
      "Breakfast each trekking morning, lunch and dinner",
      "Drinking water, tea and coffee according to the confirmed arrangement",
      "Guided trekking with wildlife and landscape interpretation",
      "Pre-trek briefing, packing guidance and Gondar pickup / drop-off",
    ],
    excluded: trekExclusions,
  },
  {
    id: "simien-essential",
    title: "Simien Essential",
    tag: "4 days · 3 nights",
    href: "/treks/4-day-simien-classic",
    linkLabel: "Explore Simien Essential",
    included: [
      "Private transportation from Gondar to Simien and return",
      "Professional English-speaking local trekking guide",
      "Simien National Park entrance fee, trekking / camping permits and scout",
      "Trekking tents, sleeping mattresses, dining tent where required",
      "Cooking and camp equipment, professional trekking cook and camp support crew",
      "Mule support, breakfast, lunch and dinner",
      "Drinking water, tea and coffee during camping",
      "All agreed trekking support, pre-trip briefing and packing guidance",
      "Gondar pickup / drop-off",
    ],
    excluded: trekExclusions,
  },
  {
    id: "ras-dashen-challenge",
    title: "Ras Dashen Challenge",
    tag: "6 days · 5 nights",
    href: "/treks/ras-dashen-challenge",
    linkLabel: "Explore the Ras Dashen Challenge",
    included: [
      "Gondar–Simien transportation and transfers to/from the agreed trekking route",
      "Professional English-speaking trekking guide",
      "Simien National Park entrance fees, required permits and scout",
      "Camping throughout the trek: tents, mattresses, dining / cooking equipment",
      "Professional cook, camping support crew, mule support and handlers",
      "Breakfast, lunch and dinner, drinking water, tea and coffee",
      "The Ras Dashen summit attempt with route guidance and mountain interpretation",
      "Pre-trek briefing, packing guidance and Gondar coordination",
    ],
    excluded: [...trekExclusions, "High-altitude / evacuation-specific insurance"],
    note: "Ras Dashen summit success cannot be guaranteed. Safety conditions determine the final summit decision.",
  },
  {
    id: "ras-dashen-expedition",
    title: "Ras Dashen Expedition",
    tag: "7 days · 6 nights",
    href: "/ras-dashen",
    linkLabel: "Read about the full Ras Dashen trek",
    intro: "Everything in the Ras Dashen Challenge, plus one additional acclimatization day and trekking night.",
    included: [
      "Everything included in the Ras Dashen Challenge",
      "Additional trekking day and camping night",
      "Additional trekking meals",
      "Full mountain support across the extended itinerary",
      "Extra time for acclimatization and flexible pacing where appropriate",
      "Mule and camp support for the additional trekking period",
    ],
    excluded: [...trekExclusions, "High-altitude / evacuation-specific insurance"],
    excludedNote: "Same exclusions as the Ras Dashen Challenge unless stated otherwise in your quotation.",
    note: "Ras Dashen summit success cannot be guaranteed. Safety conditions determine the final summit decision.",
  },
  {
    id: "simien-ras-dashen-8day",
    title: "Simien & Ras Dashen",
    tag: "8 days · 7 nights",
    href: "/ras-dashen",
    linkLabel: "Read about the full Ras Dashen trek",
    intro: "For travelers who want both the classic Simien route and the Ras Dashen summit in one journey.",
    included: [
      "Gondar–Simien transportation and route-dependent return transportation",
      "Professional trekking guide, park entrance fees, permits and scout",
      "Camping throughout the route: tents, mattresses, dining / cooking equipment",
      "Professional cook, camp support crew, mule support and handlers",
      "Breakfast, lunch and dinner, drinking water, tea and coffee",
      "The Ras Dashen summit attempt with route guidance",
      "Wildlife and landscape interpretation",
      "Pre-trek briefing and packing guidance",
    ],
    excluded: [...trekExclusions, "High-altitude / evacuation-specific insurance"],
    note: "Ras Dashen summit success cannot be guaranteed. Safety conditions determine the final summit decision.",
  },
  {
    id: "full-simien",
    title: "Full Simien Journey",
    tag: "10 days · 9 nights",
    href: "/treks/10-day-simien-ras-dashen",
    linkLabel: "Explore the 10-day expedition",
    included: [
      "Private transportation from Gondar to the mountains, and from Adi Arkay back to Gondar",
      "Professional English-speaking trekking guide, park scout, entrance fees and permits",
      "Trekking tents, sleeping mattresses, dining and cooking equipment",
      "Professional cook, camping crew, mule support and handlers",
      "Breakfast, lunch and dinner throughout the trekking program",
      "Drinking water, tea and coffee according to the confirmed arrangement",
      "The Ras Dashen summit attempt with route planning and coordination",
      "Wildlife and landscape interpretation",
      "Pre-trek briefing, packing guidance and Gondar pickup / drop-off",
    ],
    excluded: [...trekExclusions, "Professional photography / video services"],
    note: "Ras Dashen summit success cannot be guaranteed. Safety conditions determine the final summit decision.",
  },
  {
    id: "simien-wildlife",
    title: "Simien Wildlife Journey",
    tag: "2–4 days",
    included: [
      "Gondar–Simien–Gondar transportation",
      "Professional local wildlife / trekking guide",
      "Park entrance fees, required scout and trekking permits where applicable",
      "Camping or accommodation according to the itinerary",
      "Meals and drinking water according to the itinerary",
      "Wildlife-focused walking and interpretation",
      "Local landscape and cultural interpretation",
      "Pre-trip planning",
    ],
    excluded: dayTripExclusions,
    note: "Wildlife sightings are never guaranteed.",
  },
  {
    id: "photographers-simien",
    title: "Photographer's Simien",
    tag: "3–5 days",
    href: "/simien-photography-tour",
    linkLabel: "Explore Simien photography journeys",
    included: [
      "Private transportation according to the itinerary",
      "Professional local guide, park fees and required scout",
      "Camping / accommodation and equipment according to the itinerary",
      "Meals and drinking water, mule support where applicable",
      "Local wildlife and landscape knowledge",
      "Flexible photographic stops within reasonable route limits",
      "Pre-trip photography planning",
    ],
    excluded: [...dayTripExclusions, "Professional photographer unless specifically booked", "Camera / lens rental unless arranged", "Drone services"],
  },
  {
    id: "light-of-simien",
    title: "The Light of Simien",
    tag: "4–6 days",
    included: [
      "Private transportation and professional local guide",
      "Required park scout, park fees and permits",
      "Accommodation / camping and equipment according to the itinerary",
      "Meals and drinking water, mule support where applicable",
      "Flexible daily pacing within the planned route",
      "Local photography guidance and landscape interpretation",
      "Pre-trip planning",
    ],
    excluded: [...dayTripExclusions, "Professional photographer unless booked", "Camera equipment and drone services"],
  },
  {
    id: "slow-simien",
    title: "The Slow Simien",
    tag: "4–7 days",
    included: [
      "Private transportation and professional local guide",
      "Park fees, required permits and scout",
      "Camping or lodge accommodation according to the itinerary",
      "Cook and camping crew where required, mule support where applicable",
      "Breakfast, lunch and dinner, drinking water, tea and coffee during camping",
      "A slower trekking pace with extra time for observation and photography",
      "Wildlife and landscape interpretation",
      "Pre-trip preparation",
    ],
    excluded: [...trekExclusions.filter((item) => item !== "Medical treatment and emergency evacuation")],
  },
  {
    id: "sleep-under-simien-sky",
    title: "Sleep Under the Simien Sky",
    tag: "2–4 nights",
    included: [
      "Transportation according to the itinerary and professional local guide",
      "Park entrance fees, required scout and camping permits",
      "Camping tents, sleeping mattresses, dining / cooking equipment",
      "Camp crew and cook, mule support where required",
      "Breakfast, lunch and dinner, drinking water, tea and coffee",
      "Camp setup and breakdown, local mountain interpretation",
    ],
    excluded: dayTripExclusions,
  },
  {
    id: "private-simien",
    title: "Private Simien",
    tag: "Your dates, your pace",
    intro: "Exact inclusions are customized to your itinerary. This can normally include:",
    included: [
      "Private transportation and professional local guide",
      "Park fees, required scout and trekking permits",
      "Camping or hotel / lodge accommodation and equipment where applicable",
      "Cook and camp crew where required, mule support where required",
      "Meals and drinking water according to the itinerary",
      "Pre-trip planning and a personalized itinerary",
      "Gondar coordination",
    ],
    excluded: dayTripExclusions,
    excludedNote: "Exact exclusions are confirmed in your personalized quotation.",
  },
  {
    id: "gondar-essentials",
    title: "Gondar Essentials",
    tag: "Half day / full day",
    href: "/gondar",
    linkLabel: "Explore Gondar tours",
    included: [
      "Professional local English-speaking guide",
      "Private transportation according to the itinerary",
      "Gondar hotel pickup and drop-off, driver and fuel",
      "Entrance fees to attractions specifically listed in your itinerary",
      "Historical and cultural interpretation",
      "Personalized sightseeing route and pre-trip coordination",
    ],
    excluded: cityTourExclusions,
  },
  {
    id: "royal-gondar",
    title: "Royal Gondar",
    tag: "Follow the royal story",
    href: "/gondar#what-to-see",
    linkLabel: "See what to visit in Gondar",
    included: [
      "Professional local guide and private transportation",
      "Hotel pickup / drop-off, driver and fuel",
      "Fasil Ghebbi entrance fee when included in the itinerary",
      "Other listed historical-site entrance fees",
      "Historical interpretation, cultural context and personalized sightseeing",
    ],
    excluded: cityTourExclusions,
  },
  {
    id: "gondar-food-coffee",
    title: "Gondar Food & Coffee",
    tag: "Taste the city",
    href: "/gondar#experiences",
    linkLabel: "Explore Gondar food & coffee",
    included: [
      "Local guide and transportation where required",
      "Planned food / coffee experiences specifically listed in the itinerary",
      "Ethiopian coffee experience where stated",
      "Cultural interpretation and local food introduction",
      "Hotel pickup / drop-off where included",
    ],
    excluded: ["Additional food and drinks outside the agreed experience", "Alcohol", "Personal purchases", "Tips", "Flights, visa and insurance", "Optional experiences"],
  },
  {
    id: "gondar-simien",
    title: "Gondar + Simien",
    tag: "History → culture → mountains",
    href: "/treks/gondar-heritage-simien",
    linkLabel: "Explore Gondar, Heritage & Simien",
    included: [
      "Private transportation and professional local guide",
      "Gondar sightseeing and applicable attraction entrance fees",
      "Simien National Park entrance fee, required scout and trekking permits",
      "Camping or accommodation and equipment according to the itinerary",
      "Meals and drinking water according to the itinerary",
      "Mule support and cook / camp crew where required",
      "Pre-trip planning",
    ],
    excluded: [...comboExclusions, "Extra hotel nights"],
  },
  {
    id: "gondar-simien-ras-dashen",
    title: "Gondar + Simien + Ras Dashen",
    tag: "City → mountains → summit",
    href: "/ras-dashen",
    linkLabel: "Read about the Ras Dashen trek",
    included: [
      "Private ground transportation and professional local guide",
      "Gondar sightseeing and listed attraction entrance fees",
      "Simien National Park fees, trekking permits and required scout",
      "Camping accommodation: tents, mattresses, cooking equipment",
      "Professional cook, camp crew and mule support",
      "Breakfast, lunch and dinner, drinking water, tea and coffee",
      "The Ras Dashen summit attempt",
      "Pre-trip planning",
    ],
    excluded: [...trekExclusions, "High-altitude / evacuation-specific insurance"],
    note: "Ras Dashen summit success cannot be guaranteed. Safety conditions determine the final summit decision.",
  },
  {
    id: "gondar-simien-lalibela",
    title: "Gondar + Simien + Lalibela",
    tag: "Mountains & sacred stone",
    included: [
      "Private ground transportation according to the itinerary",
      "Professional local guide(s)",
      "Gondar sightseeing and listed entrance fees",
      "Simien National Park fees, required trekking permits and scout",
      "Trekking / camping support where applicable",
      "Hotels / accommodation according to the confirmed itinerary",
      "Meals according to the itinerary, drinking water during trekking",
      "Domestic transportation only if specifically included",
      "Pre-trip planning",
    ],
    excluded: comboExclusions,
  },
  {
    id: "gondar-simien-lake-tana",
    title: "Gondar + Simien + Lake Tana",
    tag: "Mountains & sacred waters",
    href: "/gondar#what-to-see",
    linkLabel: "See Gorgora & Lake Tana",
    included: [
      "Private ground transportation and professional guides",
      "Gondar sightseeing and listed entrance fees",
      "Simien National Park fees, required trekking permits and scout",
      "Accommodation and meals according to the itinerary",
      "Boat services only when specifically included",
      "Trekking and mule support where applicable",
      "Pre-trip planning",
    ],
    excluded: [...comboExclusions, "Optional boat excursions not listed"],
  },
  {
    id: "gondar-simien-aksum",
    title: "Gondar + Simien + Aksum",
    tag: "Kingdoms & mountains",
    included: [
      "Private ground transportation according to the itinerary",
      "Professional guides, Gondar sightseeing and listed entrance fees",
      "Simien National Park fees, required permits and scout",
      "Accommodation and meals according to the itinerary",
      "Trekking equipment and mule support where applicable",
      "Drinking water during trekking",
      "Pre-trip planning",
    ],
    excluded: comboExclusions,
  },
  {
    id: "northern-highlights",
    title: "Northern Ethiopia Highlights",
    tag: "A full northern journey",
    intro: "Exact inclusions depend on the itinerary. A typical package includes:",
    included: [
      "Private transportation and professional local guides",
      "Gondar sightseeing and listed attraction entrance fees",
      "Simien National Park fees, required permits and scout",
      "Trekking support where applicable, hotels / lodges or camping according to the itinerary",
      "Meals according to the itinerary, drinking water during trekking",
      "Mule support where required",
      "Domestic flights only when specifically included",
      "Airport and transport transfers according to the itinerary",
      "Pre-trip planning and a personalized itinerary",
    ],
    excluded: [...comboExclusions, "Additional accommodation"],
  },
  {
    id: "group-tours",
    title: "Group Tours",
    tag: "Travel together",
    intro: "Exact inclusions are shown on each group departure page. Depending on the departure, this can include:",
    included: [
      "Group transportation and professional trekking guide",
      "Park entrance fees, required scout and trekking permits",
      "Camping accommodation and equipment, cook / camp crew",
      "Mule support where applicable",
      "Meals and drinking water according to the itinerary",
      "Listed accommodation and sightseeing entrance fees",
      "Pre-trip coordination and group briefing",
    ],
    excluded: [...comboExclusions, "Extra hotel nights"],
  },
];
