import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "@/components/PageShell";
import { EditorialHero, FeatureGrid, PageLinks, PlanningCall, SectionIntro, StorySection } from "@/components/Editorial";

export const metadata: Metadata = { title: "Where to Stay in Gondar & Simien Mountains | Hotels, Lodges & Camping", description: "Plan Gondar hotels, Debark stops, Simien lodges and mountain camping around your trek. Local advice for the nights before, during and after the adventure.", alternates: { canonical: "/where-to-stay-gondar-simien" } };

export default function AccommodationPage() {
  return <PageShell lightHeader={false}>
    <EditorialHero eyebrow="Where to stay · Gondar & Simien" title="Before the mountains." accent="After the adventure." lead="A city hotel, a mountain lodge or a tent beneath the highland sky. Choose your stays around the whole journey, your comfort and your time." image={{ src: "/images/geech-camp.jpg", alt: "Trekking tents at Geech camp in the Simien Mountains" }} parent={{ label: "Field notes", href: "/travel-guide" }} />
    <PageLinks items={[{ label: "Gondar stays", href: "#gondar" }, { label: "Simien stays", href: "#simien" }, { label: "Debark", href: "#debark" }, { label: "Choose your stay", href: "#choose" }]} />
    <section className="section" id="gondar"><div className="shell"><SectionIntro tag="Your gateway to the mountains" title="Start with" accent="a night in Gondar." /><p className="content-lead">Rest after arrival, meet your guide, organize luggage and equipment, and prepare for the road north. Leave time for the city’s royal history, food and coffee too.</p><FeatureGrid columns={2} items={[
      { title: "Comfort & resort stays", body: "For travelers who want a more comfortable base before or after a trek. Discuss room comfort, restaurant access, relaxing spaces and transport needs." },
      { title: "Mid-range hotels", body: "A practical balance for many travelers. Compare location, private rooms, bathroom arrangements, breakfast and value for your dates." },
      { title: "Guesthouses & smaller stays", body: "Consider a more personal atmosphere and local character, whether you are traveling independently, staying longer or hoping to meet other travelers." },
      { title: "Budget accommodation", body: "Keep more of your budget for guiding and experiences while choosing a practical place for rest and an early departure." },
    ]} />
    <div className="accommodation-options"><h3 className="content-subtitle">Independent options to discuss</h3><p>These are accommodation options, not a list of confirmed commercial partners. Ask us to check their current suitability and availability for your itinerary.</p><ul className="editorial-list"><li><strong>Goha Hotel</strong> — a Gondar hotel option to discuss with the local team.</li><li><strong>Haile Resort — Gondar / Bileko</strong> — a resort-style option. <a href="https://hailehotelsandresorts.com/about-us" target="_blank" rel="noreferrer">Official hotel group</a>.</li><li><strong>Gondar Plaza Hotel</strong> — a city hotel option. <a href="https://www.gondarplaza.com/" target="_blank" rel="noreferrer">Official hotel information</a>.</li><li><strong>Gondar Backpackers</strong> — an option to discuss for a budget or social stay.</li><li><strong>Inn of the Four Sisters</strong> — a smaller lodging option to discuss.</li></ul><p className="content-note">Facilities, operating arrangements, prices and availability are checked for your dates before a stay is proposed.</p></div>
    </div></section>
    <section className="section section--paper" id="simien"><div className="shell"><SectionIntro tag="Your bedroom changes with the landscape" title="Stay closer" accent="to the mountains." /><FeatureGrid items={[
      { title: "Mountain lodges", body: "A lodge can suit travelers who prefer more comfort, short walks and a base close to the scenery. It does not replace the camps required for every longer trekking route.", href: "/plan?experience=accommodation", linkLabel: "Ask about a lodge stay" },
      { title: "Trekking camps", body: "Sankaber, Geech, Chenek and other established areas can become overnight stops along your confirmed route. Camping lets you continue through the landscape instead of returning to a hotel each evening.", href: "/treks", linkLabel: "Explore camping treks" },
      { title: "Basic mountain stays", body: "Simple huts or refuge-style stays may be available on some routes. Facilities and operation vary, so the team checks the actual option before including it in a plan.", href: "/plan?experience=accommodation", linkLabel: "Discuss your route" },
    ]} /><p className="content-note"><strong>Simien Lodge</strong> describes its location at the edge of the escarpment. Check the <a href="https://www.simiens.com/" target="_blank" rel="noreferrer">lodge’s own information</a> and ask how a stay fits your route. Mountain nights can be cold; confirm your clothing and sleeping equipment with the team.</p></div></section>
    <StorySection id="debark" tag="Between city and mountain" title="Does a night in Debark" accent="make sense?" paragraphs={[
      "Debark is the practical gateway for park arrangements, guides, scouts, supplies and transport. A night there can help when arrival is late or your plan needs an early start near the park.",
      "Staying in Gondar gives more city time and accommodation choice. Staying near the park can suit shorter programs or lodge-based experiences. Your arrival time, route and departure schedule determine which works best.",
      "After a longer trek, a night back in Gondar can leave time for rest, a comfortable meal and your onward plans. We can coordinate both the pre-trek and post-trek stays.",
    ]}><Link className="text-link" href="/plan?experience=accommodation">Ask about your arrival and route</Link></StorySection>
    <section className="section section--paper" id="choose"><div className="shell"><SectionIntro tag="The right stay is personal" title="Match the night" accent="to the journey." /><div className="table-scroll"><table className="editorial-table"><caption>Starting points for choosing accommodation</caption><thead><tr><th scope="col">Your priorities</th><th scope="col">A style to discuss</th></tr></thead><tbody>
      <tr><th scope="row">Extra comfort</th><td>Resort or higher-comfort hotel</td></tr><tr><th scope="row">Couples & families</th><td>Comfortable hotel or lodge with suitable room arrangements</td></tr><tr><th scope="row">Budget or longer stays</th><td>Guesthouse or practical budget accommodation</td></tr><tr><th scope="row">Before & after trekking</th><td>A hotel suited to rest, preparation and transfers</td></tr><tr><th scope="row">Photography & short mountain visits</th><td>A base matched to your locations and light</td></tr><tr><th scope="row">Long Simien journeys</th><td>Camping with selected hotel or lodge nights where the route allows</td></tr>
    </tbody></table></div><p className="content-lead">Tell us your arrival date, group size, nights in Gondar and Simien, trekking duration, budget and preferred accommodation. We will bring the stays, transfers and mountain route together in your quotation.</p><Link className="button button--dark" href="/plan?experience=accommodation">Plan my stay</Link></div></section>
    <PlanningCall title="Tell us your itinerary. We’ll help you choose where to stay." experience="accommodation" label="Request a complete trip quote" />
  </PageShell>;
}
