export const experienceLinks = [
  { title: "Gondar, Heritage & Simien", tag: "5 days · 4 nights", body: "Castles, churches and Woleka heritage, followed by two nights in the Simien highlands.", href: "/treks/gondar-heritage-simien" },
  { title: "The full Simien expedition", tag: "10 days · 9 nights", body: "Walk the escarpment, attempt Ras Dashen and continue through the valleys toward Adi Arkay.", href: "/treks/10-day-simien-ras-dashen" },
  { title: "Festivals & holiday journeys", tag: "Living culture", body: "Experience Timkat, Genna, Meskel or Enkutatash with local interpretation and time in the mountains.", href: "/gondar" },
  { title: "Hidden Gondar running", tag: "Easy · Active · Trail", body: "Follow quieter paths, farmland and highland views with a local running guide, at your own pace.", href: "/gondar/gondar" },
  { title: "Simien photography", tag: "1 to 5 days · Flexible", body: "Build a journey around landscapes, wildlife and changing light, with time to walk, watch and wait.", href: "/gallery" },
  { title: "Gondar through local eyes", tag: "History · Food · Community", body: "Connect royal heritage with coffee, markets, neighbourhoods and the countryside around the city.", href: "/gondar/gondar" },
] as const;

export const planningOptions = [
  { id: "simien-day", label: "Simien in a Day" },
  { id: "simien-classic", label: "The Simien Classic — 3 days" },
  { id: "simien-essential", label: "Simien Classic — 4 days" },
  { id: "ras-dashen", label: "Ras Dashen — summit approach & return planning" },
  { id: "simien-two-day", label: "Two-day Simien mountain escape" },
  { id: "gondar-royal-mountains", label: "Gondar Royal City & Mountains — 5 days" },
  { id: "full-simien", label: "Simien & Ras Dashen Expedition — 10 days" },
  { id: "gondar-heritage-simien", label: "Gondar, Heritage & Simien — 5 days" },
  { id: "festivals", label: "Festivals & holiday journeys" },
  { id: "timkat-simien", label: "Timkat & Simien — 6 days" },
  { id: "timkat-ras-dashen", label: "Timkat & Ras Dashen — 8–10 days" },
  { id: "genna-simien", label: "Genna & Simien — 6–8 days" },
  { id: "meskel-simien", label: "Meskel & Simien" },
  { id: "enkutatash-simien", label: "Enkutatash & Simien" },
  { id: "gondar-running", label: "Hidden Gondar running experience" },
  { id: "photography", label: "Simien photography journey" },
  { id: "photo-day", label: "1-day Simien photography experience" },
  { id: "photo-wildlife", label: "2–3 day wildlife & landscape photography" },
  { id: "photo-expedition", label: "4–5 day photography expedition" },
  { id: "gondar", label: "Build my Gondar experience" },
  { id: "royal-gondar", label: "Royal Gondar experience" },
  { id: "local-gondar", label: "Gondar through local eyes" },
  { id: "food-coffee", label: "Gondar food & coffee" },
  { id: "gondar-photo", label: "Gondar photography walk" },
  { id: "history-culture", label: "Gondar history & culture" },
  { id: "market-life", label: "Gondar market & local life" },
  { id: "kosoye", label: "Gondar & Kosoye highlands" },
  { id: "community", label: "Village & community experience" },
  { id: "accommodation", label: "Gondar & Simien accommodation" },
  { id: "travel-services", label: "Transport, guiding & travel services" },
  { id: "custom", label: "Custom northern Ethiopia journey" },
] as const;

export const gondarExperiences = [
  { id: "royal-gondar", title: "Royal Gondar experience", categories: ["History", "Culture"], body: "Explore Fasil Ghebbi and the royal city with the stories of its emperors, architecture and court life. Connect the historic compound to the Gondar around it.", fit: "First visits, history lovers and architectural photography" },
  { id: "local-gondar", title: "Gondar through local eyes", categories: ["Local life", "Culture"], body: "Walk through neighbourhoods, visit small businesses and share coffee and conversation. Your guide introduces the everyday city they live in.", fit: "Travelers who value conversation and an unhurried pace" },
  { id: "food-coffee", title: "Food & coffee experience", categories: ["Food", "Coffee", "Culture"], body: "Follow coffee roasting, local ingredients and the stories behind injera, spices and shared meals. Coffee preparation, food markets and traditional dishes can shape the day.", fit: "Curious eaters and coffee lovers; tell us your dietary needs" },
  { id: "gondar-photo", title: "Gondar photography walk", categories: ["Photography", "Local life"], body: "Look for morning light on stone walls, opening shops and quieter streets. There is time for photographs and conversations, with permission before photographing people.", fit: "Phone photographers, enthusiasts and visual storytellers" },
  { id: "history-culture", title: "History & culture tour", categories: ["History", "Culture"], body: "Connect churches, religious traditions, architecture, trade, art and music with modern Ethiopian life. The route follows the stories that interest you most.", fit: "Travelers who want a deeper historical and cultural context" },
  { id: "market-life", title: "Market & local life", categories: ["Food", "Local life"], body: "Explore market areas when conditions and trading days suit. Learn about local products, farming connections and how goods move between Gondar and the highlands.", fit: "Visitors interested in food, trade and everyday city life" },
  { id: "kosoye", title: "Gondar & Kosoye highlands", categories: ["Local life", "Culture"], body: "Travel from the city into countryside, farmland and rural walking routes. Village visits, local food, coffee and family conversations are arranged respectfully with hosts.", fit: "Walkers and travelers interested in the countryside" },
  { id: "gondar-heritage-simien", title: "Gondar & Simien combination", categories: ["Gondar + Simien", "History"], body: "Begin with royal heritage, food and coffee, then follow the road through Debark into escarpments, wildlife and mountain trails. Start with our five-day heritage journey.", fit: "Travelers who want culture and mountains in one journey", href: "/treks/gondar-heritage-simien" },
] as const;
